/**
 * @file RoboCupGameControlData.h
 * The file encapsulates definitions in the file RoboCupGameControlData.h
 * that is provided with the GameController in a namespace.
 * @author Thomas Röfer
 */

#pragma once

#include <cstdint>
#include <cstring>

namespace RoboCup
{
#define fieldPlayerColour fieldPlayerColor
#define goalkeeperColour goalkeeperColor
#include <RoboCupGameControlData.h>
#undef fieldPlayerColour
#undef goalkeeperColour

// Compatibility aliases for SabanaHerons modules that still use the SPL-era names internally.
// The wire format above is the Humanoid League GameController v20 format.
#ifndef COMPETITION_PHASE_ROUNDROBIN
#define COMPETITION_PHASE_ROUNDROBIN 0
#endif
#ifndef COMPETITION_PHASE_PLAYOFF
#define COMPETITION_PHASE_PLAYOFF 1
#endif
#ifndef COMPETITION_TYPE_NORMAL
#define COMPETITION_TYPE_NORMAL COMPETITION_TYPE_LARGE
#endif
#ifndef COMPETITION_TYPE_SHARED_AUTONOMY
#define COMPETITION_TYPE_SHARED_AUTONOMY COMPETITION_TYPE_SMALL
#endif
#ifndef GAME_PHASE_PENALTYSHOOT
#define GAME_PHASE_PENALTYSHOOT GAME_PHASE_PENALTY_SHOOT_OUT
#endif
#ifndef GAME_PHASE_OVERTIME
#define GAME_PHASE_OVERTIME GAME_PHASE_EXTRA_TIME
#endif
#ifndef STATE_STANDBY
#define STATE_STANDBY STATE_INITIAL
#endif
#ifndef SET_PLAY_PUSHING_FREE_KICK
#define SET_PLAY_PUSHING_FREE_KICK SET_PLAY_DIRECT_FREE_KICK
#endif
#ifndef SET_PLAY_KICK_IN
#define SET_PLAY_KICK_IN SET_PLAY_THROW_IN
#endif
#ifndef PENALTY_SPL_ILLEGAL_BALL_CONTACT
#define PENALTY_SPL_ILLEGAL_BALL_CONTACT PENALTY_BALL_HOLDING
#endif
#ifndef PENALTY_SPL_PLAYER_PUSHING
#define PENALTY_SPL_PLAYER_PUSHING PENALTY_PUSHING
#endif
#ifndef PENALTY_SPL_ILLEGAL_MOTION_IN_SET
#define PENALTY_SPL_ILLEGAL_MOTION_IN_SET PENALTY_MOTION_IN_SET
#endif
#ifndef PENALTY_SPL_INACTIVE_PLAYER
#define PENALTY_SPL_INACTIVE_PLAYER PENALTY_INCAPABLE_ROBOT
#endif
#ifndef PENALTY_SPL_ILLEGAL_POSITION
#define PENALTY_SPL_ILLEGAL_POSITION PENALTY_ILLEGAL_POSITIONING
#endif
#ifndef PENALTY_SPL_LEAVING_THE_FIELD
#define PENALTY_SPL_LEAVING_THE_FIELD PENALTY_LEAVING_THE_FIELD
#endif
#ifndef PENALTY_SPL_REQUEST_FOR_PICKUP
#define PENALTY_SPL_REQUEST_FOR_PICKUP PENALTY_PICK_UP
#endif
#ifndef PENALTY_SPL_LOCAL_GAME_STUCK
#define PENALTY_SPL_LOCAL_GAME_STUCK PENALTY_LOCAL_GAME_STUCK
#endif
#ifndef PENALTY_SPL_ILLEGAL_POSITION_IN_SET
#define PENALTY_SPL_ILLEGAL_POSITION_IN_SET PENALTY_ILLEGAL_POSITIONING
#endif
#ifndef PENALTY_SPL_PLAYER_STANCE
#define PENALTY_SPL_PLAYER_STANCE PENALTY_CAUTIONED
#endif
#ifndef PENALTY_SPL_ILLEGAL_MOTION_IN_STANDBY
#define PENALTY_SPL_ILLEGAL_MOTION_IN_STANDBY PENALTY_MOTION_IN_STOP
#endif
#ifndef PENALTY_MANUAL
#define PENALTY_MANUAL 15
#endif
}
